<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<None Include="TestData/HyperCastCorpus/**/*.json" CopyToOutputDirectory="PreserveNewest" />
		<None Include="TestData/HyperCastCorpus/SNAPSHOT_SHA.txt" CopyToOutputDirectory="PreserveNewest" />
		<PackageReference Include="FsCheck" Version="*" />
		<ProjectReference Include="..\..\src\Primitives\Primitives.csproj" />
	</ItemGroup>
</Project>
