namespace Norse.Architecture.Analyzers.Tests;

/// <summary>
/// Real Razor-compiler generated C# output — spec Section 7's proof obligation (never a hand-authored
/// approximation of what the generator "probably" emits). Captured against SDK
/// 11.0.100-preview.6.26359.118 (`dotnet --version`) via a throwaway scratch Razor class library,
/// never committed:
///
/// 1. `fixture.csproj` - `Microsoft.NET.Sdk.Razor`, `TargetFramework=net11.0`, `Nullable=enable`,
///    `EmitCompilerGeneratedFiles=true`, `PackageReference Microsoft.AspNetCore.Components.Web 11.*-*`.
/// 2. `StubForm.cs` (the seam-shape stub - `protected EditContext EditContextFor(object request)`,
///    the same name Asgard's real seam uses; Svartalfheim can never reference Asgard, so the fixture
///    stubs the shape instead of the type), `ViolatingForm.razor` (`@inherits Fixture.StubForm` +
///    `EditContext="EditContextFor(_request)"` + `OnValidSubmit="Handle"`), `CleanForm.razor`
///    (identical but `OnSubmit="Handle"`), `ModelBoundForm.razor` (`Model="_request"` +
///    `OnValidSubmit="Handle"` - the scaffold shape NORSE075 must NOT convict), and an `_Imports.razor`
///    bringing in `Microsoft.AspNetCore.Components(.Forms/.Web)` (needed for the fixture to compile at
///    all; the brief's snippets omit it because it has no bearing on the render-tree shape below).
/// 3. `dotnet build`, then copy `obj/Debug/net11.0/generated/Microsoft.CodeAnalysis.Razor.Compiler/
///    Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/{Name}_razor.g.cs` verbatim into
///    the consts below (source encoding is UTF-8 with a BOM; the BOM itself is stripped since it is a
///    file-encoding marker, not compiled text — every other byte is unedited). The only edit made to
///    the captured text: the machine-local absolute scratch path inside the `#pragma checksum`/`#line`
///    directives is replaced with a relative `fixture/` prefix (CLAUDE.md's absolute-path law) - those
///    directives are debugger/stepping metadata only, never validated against a real file by the
///    compiler, so the edit has zero effect on what's actually under test. Raw string closing
///    delimiters below sit at column 0 (not the usual tab depth) because the captured content itself
///    contains column-0 lines (`namespace fixture`, `{`, `}`, ...) - C#'s raw-string dedent rule
///    requires the closing delimiter's indentation to be a prefix of every content line, so column 0 is
///    the only indentation that fits real generator output without rewriting it.
/// 4. Scratch project deleted after capture. Regenerate from this recipe (same four files, same steps)
///    to re-prove the analyzer's assumed generated shape against a future SDK.
///
/// The captured shape: `EditForm` parameters arrive via
/// `__builder.AddComponentParameter(ordinal, nameof(EditForm.ParameterName), TypeCheck&lt;T&gt;(value))`
/// - the parameter name is a `nameof(...)` expression, which C# constant-folds, so it still reads as a
/// constant string through `IArgumentOperation.Value.ConstantValue` exactly as a string literal would.
/// Ordinal 1 is always the parameter name, ordinal 2 the value - matching `SeamBoundFormAnalyzer`'s
/// assumed shape with no adjustment needed.
/// </summary>
static class RazorGeneratedFixtures
{
	public const string StubFormSource =
		"""
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;

namespace Fixture;

public abstract class StubForm : ComponentBase
{
	protected EditContext EditContextFor(object request) =>
		new(request);
}
""";

	public const string ViolatingForm =
		"""
#pragma checksum "fixture/ViolatingForm.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "3b4f57a369557582f9c68e6fc67aa09835fd7937fd1cf289036438e7e124c0a4"
// <auto-generated/>
#pragma warning disable 1591
namespace fixture
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,39) "fixture/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,45) "fixture/_Imports.razor"
using Microsoft.AspNetCore.Components.Forms

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,43) "fixture/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class ViolatingForm : 
#nullable restore
#line (1,11)-(1,27) "fixture/ViolatingForm.razor"
Fixture.StubForm

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Microsoft.AspNetCore.Components.Forms.EditForm>(0);
            __builder.AddComponentParameter(1, nameof(global::Microsoft.AspNetCore.Components.Forms.EditForm.
#nullable restore
#line (3,11)-(3,22) "fixture/ViolatingForm.razor"
EditContext

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.Forms.EditContext>(
#nullable restore
#line (3,24)-(3,48) "fixture/ViolatingForm.razor"
EditContextFor(_request)

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(2, nameof(global::Microsoft.AspNetCore.Components.Forms.EditForm.
#nullable restore
#line (3,50)-(3,63) "fixture/ViolatingForm.razor"
OnValidSubmit

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::Microsoft.AspNetCore.Components.Forms.EditContext>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Forms.EditContext>(this, 
#nullable restore
#line (3,65)-(3,71) "fixture/ViolatingForm.razor"
Handle

#line default
#line hidden
#nullable disable
            )));
            __builder.CloseComponent();
        }
        #pragma warning restore 1998
#nullable restore
#line (5,8)-(8,1) "fixture/ViolatingForm.razor"

	readonly object _request = new();
	void Handle(EditContext context) { }

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
""";

	public const string CleanForm =
		"""
#pragma checksum "fixture/CleanForm.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0dd6c8de44c8260ba6f49f139571e5651eeeedf1a1b29a48ae11bec7c5c984d9"
// <auto-generated/>
#pragma warning disable 1591
namespace fixture
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,39) "fixture/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,45) "fixture/_Imports.razor"
using Microsoft.AspNetCore.Components.Forms

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,43) "fixture/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class CleanForm : 
#nullable restore
#line (1,11)-(1,27) "fixture/CleanForm.razor"
Fixture.StubForm

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Microsoft.AspNetCore.Components.Forms.EditForm>(0);
            __builder.AddComponentParameter(1, nameof(global::Microsoft.AspNetCore.Components.Forms.EditForm.
#nullable restore
#line (3,11)-(3,22) "fixture/CleanForm.razor"
EditContext

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.Forms.EditContext>(
#nullable restore
#line (3,24)-(3,48) "fixture/CleanForm.razor"
EditContextFor(_request)

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(2, nameof(global::Microsoft.AspNetCore.Components.Forms.EditForm.
#nullable restore
#line (3,50)-(3,58) "fixture/CleanForm.razor"
OnSubmit

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::Microsoft.AspNetCore.Components.Forms.EditContext>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Forms.EditContext>(this, 
#nullable restore
#line (3,60)-(3,66) "fixture/CleanForm.razor"
Handle

#line default
#line hidden
#nullable disable
            )));
            __builder.CloseComponent();
        }
        #pragma warning restore 1998
#nullable restore
#line (5,8)-(8,1) "fixture/CleanForm.razor"

	readonly object _request = new();
	void Handle(EditContext context) { }

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
""";

	public const string ModelBoundForm =
		"""
#pragma checksum "fixture/ModelBoundForm.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "9b6b89748055df05c415fcbbd12856dfa035c3697537e42a33bf0e245f1863f4"
// <auto-generated/>
#pragma warning disable 1591
namespace fixture
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,39) "fixture/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,45) "fixture/_Imports.razor"
using Microsoft.AspNetCore.Components.Forms

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,43) "fixture/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class ModelBoundForm : 
#nullable restore
#line (1,11)-(1,27) "fixture/ModelBoundForm.razor"
Fixture.StubForm

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Microsoft.AspNetCore.Components.Forms.EditForm>(0);
            __builder.AddComponentParameter(1, nameof(global::Microsoft.AspNetCore.Components.Forms.EditForm.
#nullable restore
#line (3,11)-(3,16) "fixture/ModelBoundForm.razor"
Model

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Object>(
#nullable restore
#line (3,18)-(3,26) "fixture/ModelBoundForm.razor"
_request

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(2, nameof(global::Microsoft.AspNetCore.Components.Forms.EditForm.
#nullable restore
#line (3,28)-(3,41) "fixture/ModelBoundForm.razor"
OnValidSubmit

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::Microsoft.AspNetCore.Components.Forms.EditContext>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Forms.EditContext>(this, 
#nullable restore
#line (3,43)-(3,49) "fixture/ModelBoundForm.razor"
Handle

#line default
#line hidden
#nullable disable
            )));
            __builder.CloseComponent();
        }
        #pragma warning restore 1998
#nullable restore
#line (5,8)-(8,1) "fixture/ModelBoundForm.razor"

	readonly object _request = new();
	void Handle(EditContext context) { }

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
""";
}
