using System.Data.SqlTypes;
using System.Security.Cryptography;
using Norse.Primitives.Identifiers;

namespace Norse.Primitives.Tests.Identifiers;

public sealed class SequentialGuidBytesTests
{
	[Fact]
	void Should_produce_a_well_formed_version7_guid_when_generated()
	{
		var value = SequentialGuidBytes.GenerateRfc(1_800_000_000_000L, 42, new byte[6]);

		GuidVersionBits.HasVersionAndVariant(value, 7).ShouldBeTrue();
	}

	[Theory]
	[InlineData(-1L)]
	[InlineData(0x0001_0000_0000_0000L)]
	void Should_throw_when_timestamp_is_out_of_the_48_bit_range(long unixMilliseconds) =>
		Should.Throw<ArgumentOutOfRangeException>(() =>
			SequentialGuidBytes.GenerateRfc(unixMilliseconds, 0, new byte[6]));

	[Fact]
	void Should_throw_when_entropy_is_not_six_bytes() =>
		Should.Throw<ArgumentException>(() =>
			SequentialGuidBytes.GenerateRfc(0, 0, new byte[5]));

	[Fact]
	void Should_embed_the_exact_timestamp_and_counter_supplied()
	{
		// Read the generated bytes back out manually (native layout) to prove the RFC layout
		// documented on SequentialGuidBytes is exactly what GenerateRfc produces.
		const long UnixMilliseconds = 1_750_000_000_123L;
		const int Counter = 0x2A_BCDE; // arbitrary 26-bit value within range

		var value = SequentialGuidBytes.GenerateRfc(UnixMilliseconds, Counter, [1, 2, 3, 4, 5, 6]);

		Span<byte> native = stackalloc byte[16];
		value.TryWriteBytes(native);

		// native[3,2,1,0] = rfc timestamp bytes 0..3 (Data1 4-byte reversal); native[5,4] = rfc bytes 4,5.
		var readBackMs =
			((long)native[3] << 40) | ((long)native[2] << 32) | ((long)native[1] << 24) |
			((long)native[0] << 16) | ((long)native[5] << 8) | native[4];
		readBackMs.ShouldBe(UnixMilliseconds);

		// native[7] bottom nibble + native[6] = rand_a (ctrHi, top 12 bits of the 26-bit counter);
		// native[8] bottom 6 bits + native[9] = rand_b-start (ctrLo, bottom 14 bits).
		var ctrHi = ((native[7] & 0x0F) << 8) | native[6];
		var ctrLo = ((native[8] & 0x3F) << 8) | native[9];
		var readBackCounter = (ctrHi << 14) | ctrLo;
		readBackCounter.ShouldBe(Counter & 0x3FFFFFF);
	}

	[Fact]
	void Should_round_trip_through_sql_order_and_back_for_many_generated_values()
	{
		Span<byte> msBytes = stackalloc byte[6];
		for (var trial = 0; trial < 2000; trial++)
		{
			RandomNumberGenerator.Fill(msBytes);
			var unixMilliseconds =
				((long)msBytes[0] << 40) | ((long)msBytes[1] << 32) | ((long)msBytes[2] << 24) |
				((long)msBytes[3] << 16) | ((long)msBytes[4] << 8) | msBytes[5];
			var counter = RandomNumberGenerator.GetInt32(0, 0x400_0000);
			var entropy = new byte[6];
			RandomNumberGenerator.Fill(entropy);

			var rfcGuid = SequentialGuidBytes.GenerateRfc(unixMilliseconds, counter, entropy);
			var sqlGuid = SequentialGuidBytes.ToSqlOrder(rfcGuid);
			var roundTripped = SequentialGuidBytes.ToRfcOrder(sqlGuid);

			roundTripped.ShouldBe(rfcGuid);
		}
	}

	[Fact]
	void Should_keep_version_and_variant_bits_fixed_when_converted_to_sql_order()
	{
		var rfcGuid = SequentialGuidBytes.GenerateRfc(1_800_000_000_000L, 123, [1, 2, 3, 4, 5, 6]);
		var sqlGuid = SequentialGuidBytes.ToSqlOrder(rfcGuid);

		GuidVersionBits.HasVersionAndVariant(rfcGuid, 7).ShouldBeTrue();
		GuidVersionBits.HasVersionAndVariant(sqlGuid, 7).ShouldBeTrue();
	}

	[Fact]
	void Should_sort_correctly_under_sql_server_semantics_across_a_counter_carry_boundary()
	{
		// The counter's mirrored 14/12 repack exists specifically so ordering survives the
		// 12-bit carry boundary (0xFFF -> 0x1000) under SQL Server's comparison, not just plain Guid's.
		const long FixedMs = 1_800_000_000_000L;
		IList<(int Counter, SqlGuid Sql)> sequence = [];
		for (var counter = 4090; counter <= 4100; counter++)
		{
			var entropy = new byte[6];
			RandomNumberGenerator.Fill(entropy);
			var rfcGuid = SequentialGuidBytes.GenerateRfc(FixedMs, counter, entropy);
			var sqlGuid = SequentialGuidBytes.ToSqlOrder(rfcGuid);
			sequence.Add((counter, new(sqlGuid)));
		}

		int[]
			byCounter = [.. sequence.OrderBy(x => x.Counter).Select(x => x.Counter)],
			bySqlOrder = [.. sequence.OrderBy(x => x.Sql).Select(x => x.Counter)];

		bySqlOrder.ShouldBe(byCounter);
	}

	[Fact]
	void Should_sort_correctly_under_sql_server_semantics_across_a_bottom12_byte_boundary()
	{
		// Distinct from the 12-to-14-bit carry test above: this exercises byte boundaries entirely
		// WITHIN the 12-bit low counter chunk (e.g. 0x0FF -> 0x100), which never touches top14 and
		// so only catches a bug in how bottom12's own bits are split across sql[6]/sql[7].
		const long FixedMs = 1_800_000_000_000L;
		IList<(int Counter, SqlGuid Sql)> sequence = [];
		for (var counter = 0; counter <= 4200; counter++)
		{
			var entropy = new byte[6];
			RandomNumberGenerator.Fill(entropy);
			var rfcGuid = SequentialGuidBytes.GenerateRfc(FixedMs, counter, entropy);
			var sqlGuid = SequentialGuidBytes.ToSqlOrder(rfcGuid);
			sequence.Add((counter, new(sqlGuid)));
		}

		int[]
			byCounter = [.. sequence.OrderBy(x => x.Counter).Select(x => x.Counter)],
			bySqlOrder = [.. sequence.OrderBy(x => x.Sql).Select(x => x.Counter)];

		bySqlOrder.ShouldBe(byCounter);
	}

	[Fact]
	void Should_sort_correctly_under_sql_server_semantics_across_a_millisecond_boundary()
	{
		const long FixedMs = 1_800_000_000_000L;
		IList<(int Index, SqlGuid Sql)> sequence = [];
		var index = 0;
		for (var msOffset = 0; msOffset < 5; msOffset++)
		{
			for (var counter = 0; counter < 3; counter++)
			{
				var entropy = new byte[6];
				RandomNumberGenerator.Fill(entropy);
				var rfcGuid = SequentialGuidBytes.GenerateRfc(FixedMs + msOffset, counter, entropy);
				var sqlGuid = SequentialGuidBytes.ToSqlOrder(rfcGuid);
				sequence.Add((index++, new(sqlGuid)));
			}
		}

		int[]
			expected = [.. sequence.Select(x => x.Index)],
			actual = [.. sequence.OrderBy(x => x.Sql).Select(x => x.Index)];

		actual.ShouldBe(expected);
	}

	[Fact]
	void Should_extract_the_matching_timestamp_from_both_byte_orders()
	{
		const long UnixMilliseconds = 1_750_000_000_123L;
		var rfcGuid = SequentialGuidBytes.GenerateRfc(UnixMilliseconds, 7, [9, 8, 7, 6, 5, 4]);
		var sqlGuid = SequentialGuidBytes.ToSqlOrder(rfcGuid);

		var expected = DateTimeOffset.FromUnixTimeMilliseconds(UnixMilliseconds).UtcDateTime;

		SequentialGuidBytes.ExtractTimestamp(rfcGuid, GuidByteOrder.Rfc9562).ShouldBe(expected);
		SequentialGuidBytes.ExtractTimestamp(sqlGuid, GuidByteOrder.SqlServer).ShouldBe(expected);
	}
}
