using Norse.Primitives.Identifiers;

namespace Norse.Primitives.Tests.Identifiers;

public sealed class SequentialGuidBytesTests
{
	[Fact]
	void Should_produce_a_well_formed_version7_guid_when_generated()
	{
		var value = SequentialGuidBytes.GenerateRfc(1_800_000_000_000L, 42, new byte[6]);

		GuidVersionBits.HasVersionAndVariant(value, 7).ShouldBeTrue();
	}

	[Theory]
	[InlineData(-1L)]
	[InlineData(0x0001_0000_0000_0000L)]
	void Should_throw_when_timestamp_is_out_of_the_48_bit_range(long unixMilliseconds)
	{
		Should.Throw<ArgumentOutOfRangeException>(() =>
			SequentialGuidBytes.GenerateRfc(unixMilliseconds, 0, new byte[6]));
	}

	[Fact]
	void Should_throw_when_entropy_is_not_six_bytes()
	{
		Should.Throw<ArgumentException>(() =>
			SequentialGuidBytes.GenerateRfc(0, 0, new byte[5]));
	}

	[Fact]
	void Should_embed_the_exact_timestamp_and_counter_supplied()
	{
		// Read the generated bytes back out manually (native layout) to prove the RFC layout
		// documented on SequentialGuidBytes is exactly what GenerateRfc produces.
#pragma warning disable IDE1006
		const long unixMilliseconds = 1_750_000_000_123L;
		const int counter = 0x2A_BCDE; // arbitrary 26-bit value within range
#pragma warning restore IDE1006

		var value = SequentialGuidBytes.GenerateRfc(unixMilliseconds, counter, [1, 2, 3, 4, 5, 6]);

		Span<byte> native = stackalloc byte[16];
		value.TryWriteBytes(native);

		// native[3,2,1,0] = rfc timestamp bytes 0..3 (Data1 4-byte reversal); native[5,4] = rfc bytes 4,5.
		var readBackMs =
			((long)native[3] << 40) | ((long)native[2] << 32) | ((long)native[1] << 24) |
			((long)native[0] << 16) | ((long)native[5] << 8) | native[4];
		readBackMs.ShouldBe(unixMilliseconds);

		// native[7] bottom nibble + native[6] = rand_a (ctrHi, top 12 bits of the 26-bit counter);
		// native[8] bottom 6 bits + native[9] = rand_b-start (ctrLo, bottom 14 bits).
		var ctrHi = ((native[7] & 0x0F) << 8) | native[6];
		var ctrLo = ((native[8] & 0x3F) << 8) | native[9];
		var readBackCounter = (ctrHi << 14) | ctrLo;
		readBackCounter.ShouldBe(counter & 0x3FFFFFF);
	}
}
